### ISSUE TITLE
Remove trailing spaces when saving a file

### ISSUE THREAD

**Issue by brouberol** [brouberol/bo#7]

**Comment by ilmanzo** [comment]
with trailing spaces you mean empty newlines, or any trailing whitespace that occurs before the first text ? 
For example

                                   Hello World

should be saved as

`Hello World`

?

**Comment by brouberol** [comment]
I’m going to represent individual spaces as dots for that example, as I’m on my phone and I’ll probably botch the formatting otherwise.

What I meant is that the lines

```
Hello world…
Andrea
```

should be truncated to 

```
Hello world
Andrea
```

The 3 extra spaces (that `git` would probably warn you about) should be removed at save.
